### ISSUE TITLE
En el celular los ejercicios se ven muy mal

### ISSUE THREAD

**Issue by rgonzalezt** [mumuki/mumuki-puzzle-runner#5]
Las piezas se ven muuuuy grandes haciendo imposible manejarlas para resolver el ejercicio. Dejo unas capturas:

![image](https://user-images.githubusercontent.com/11671943/98291243-94102a00-1f89-11eb-81ae-38bab0ae3fcb.png)

![image](https://user-images.githubusercontent.com/11671943/98292133-fd446d00-1f8a-11eb-92e9-c513fee2355a.png)

**Comment by luchotc** [comment]
Solved by https://github.com/mumuki/mumuki-puzzle-runner/pull/7
